import {
  Home, Activity, ClipboardList, Stethoscope, Users, ShoppingBag,
  Heart, User, Search, Bell, MessageCircle, Baby, Info, Phone,
  Calendar, ChevronRight, ChevronLeft, Plus, Check, Smile, Scale, PenLine,
  FileText, Star, MapPin, Filter, Send, X, Camera, Droplet, Moon, Shield,
} from 'lucide-angular';

export const iconMap: Record<string, any> = {
  home: Home,
  activity: Activity,
  'clipboard-list': ClipboardList,
  stethoscope: Stethoscope,
  users: Users,
  'shopping-bag': ShoppingBag,
  heart: Heart,
  user: User,
  search: Search,
  bell: Bell,
  'message-circle': MessageCircle,
  baby: Baby,
  info: Info,
  phone: Phone,
  calendar: Calendar,
  'chevron-right': ChevronRight,
  'chevron-left': ChevronLeft,
  plus: Plus,
  check: Check,
  smile: Smile,
  scale: Scale,
  'pen-line': PenLine,
  'file-text': FileText,
  star: Star,
  'map-pin': MapPin,
  filter: Filter,
  send: Send,
  x: X,
  camera: Camera,
  droplet: Droplet,
  moon: Moon,
  shield: Shield,
};
